import Mathlib.GroupTheory.Coxeter.Basic

/-!
# Standard parabolic subgroups

This module defines the subgroup generated by a selected set of simple
reflections in a Coxeter system and records its smallest basic API.
-/

namespace CoxeterSystem

variable {B W : Type*} [Group W]
variable {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

/-- The standard parabolic subgroup generated by the simple reflections
indexed by `I`. -/
def standardParabolic (I : Set B) : Subgroup W :=
  Subgroup.closure (cs.simple '' I)

/-- Enlarging the set of simple generators enlarges the standard parabolic
subgroup. -/
theorem standardParabolic_mono {I J : Set B} (hIJ : I ⊆ J) :
    cs.standardParabolic I ≤ cs.standardParabolic J := by
  apply (Subgroup.closure_le (cs.standardParabolic J)).2
  intro w hw
  exact Subgroup.subset_closure (Set.image_mono hIJ hw)

@[simp]
theorem standardParabolic_empty :
    cs.standardParabolic (∅ : Set B) = ⊥ := by
  simp [standardParabolic]

@[simp]
theorem standardParabolic_univ :
    cs.standardParabolic (Set.univ : Set B) = ⊤ := by
  simpa [standardParabolic] using cs.subgroup_closure_range_simple

/-- Every selected simple reflection belongs to the generated standard
parabolic subgroup. -/
theorem simple_mem_standardParabolic {I : Set B} {i : B} (hi : i ∈ I) :
    cs.simple i ∈ cs.standardParabolic I :=
  Subgroup.subset_closure ⟨i, hi, rfl⟩

/-! A finite rank-two use-site for the canonical Coxeter system. -/

example (M : CoxeterMatrix (Fin 2)) (i : Fin 2) :
    M.toCoxeterSystem.simple i ∈
      M.toCoxeterSystem.standardParabolic (Set.univ : Set (Fin 2)) :=
  M.toCoxeterSystem.simple_mem_standardParabolic (Set.mem_univ i)

end CoxeterSystem
