import LanglandsLean.AlgebraicGeometry.HopfSpec
import LanglandsLean.AlgebraicGeometry.AlgHomPointsPresheaf
import LanglandsLean.AlgebraicGeometry.IsAlgebraicGroup
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.Algebra.MvPolynomial.Equiv
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.Away.AdjoinRoot
import Mathlib.AlgebraicGeometry.Morphisms.Affine
import Mathlib.AlgebraicGeometry.Morphisms.FiniteType
import Mathlib.RingTheory.FiniteType

/-!
# The general linear group scheme `GL_n`

For a commutative ring `R` and `n : ℕ`, the general linear group scheme
\(\operatorname{GL}_{n,R}\) is the spectrum of the localized polynomial
ring at the determinant:

\[
\operatorname{GL}_{n,R} \;=\;
  \operatorname{Spec}\bigl(R[X_{ij} : 1 \le i, j \le n][\operatorname{det}^{-1}]\bigr).
\]

The Hopf structure on this ring encodes the group structure of
\(\operatorname{GL}_n\):
- comultiplication \(\Delta(X_{ij}) = \sum_k X_{ik} \otimes X_{kj}\) (matrix
  product),
- counit \(\varepsilon(X_{ij}) = \delta_{ij}\) (identity matrix),
- antipode \(S(X_{ij}) = (\operatorname{det}^{-1}) \cdot \operatorname{adj}(X)_{ij}\)
  (Cramer's rule for matrix inverse).

## Current scope

This file ships **the underlying scheme** `GLn R n` and the
`IsAffineHom` + `LocallyOfFiniteType` instances. The `GrpObj` (Hopf
structure on the coordinate ring) is **not yet installed** — it requires:
1. Defining `Δ`, `ε`, `S` as algebra homomorphisms on `MvPolynomial`,
   extending across the localization.
2. Verifying `Δ(det) = det ⊗ det` (Cauchy-Binet for the universal
   matrix) so `Δ` extends to the localization.
3. Antipode formula via Cramer's rule (the (i,j)-entry of the inverse
   matrix involves the (j,i)-minor and a sign).
4. Checking bialgebra and Hopf axioms via the universal property of
   `MvPolynomial` (each axiom is an equation between algebra homs,
   reducible to checking on the generators `X_{ij}`).

This is a substantial follow-up (~300-500 LoC). See blueprint node
`linear_algebraic_groups.general_linear_group_scheme`.

## Main declarations

* `GLn.coordRing R n` — the coordinate ring
  `MvPolynomial (Fin n × Fin n) R` localized at the determinant.
* `GLn R n` — `Spec` of the coordinate ring, as an `Over (Spec R)`
  object.
* `GLnSch R n` — the underlying scheme.

## GitHub issue

Phase D4: <https://github.com/Langlandsproject/Langlands/issues/8>.
-/

open AlgebraicGeometry CategoryTheory Opposite MvPolynomial
open Langlands.AlgebraicGeometry.AlgHomPointsPresheaf

namespace Langlands.AlgebraicGeometry.Examples

universe u

variable (R : CommRingCat.{u}) (n : ℕ)

/-- The universal `n × n` matrix over the polynomial ring on `Fin n × Fin n`
indeterminates: the matrix whose `(i, j)`-entry is `MvPolynomial.X (i, j)`. -/
noncomputable def GLn.universalMatrix :
    Matrix (Fin n) (Fin n) (MvPolynomial (Fin n × Fin n) R) :=
  Matrix.of fun i j => MvPolynomial.X (i, j)

/-- The determinant of the universal `n × n` matrix; a polynomial in
`R[X_{ij}]`. -/
noncomputable def GLn.det : MvPolynomial (Fin n × Fin n) R :=
  (GLn.universalMatrix R n).det

/-- The coordinate ring of `GL_n`: localize `R[X_{ij}]` at the
determinant of the universal matrix. -/
noncomputable def GLn.coordRing : Type u :=
  Localization.Away (GLn.det R n)

noncomputable instance : CommRing (GLn.coordRing R n) :=
  inferInstanceAs (CommRing (Localization.Away (GLn.det R n)))

noncomputable instance : Algebra R (GLn.coordRing R n) :=
  inferInstanceAs (Algebra R (Localization.Away (GLn.det R n)))

/-- `GL_{n,R} = Spec R[X_{ij}, det^{-1}]` over `Spec R`. Built directly
via `Spec.map` of the structure morphism (we do not yet have a
`HopfAlgebra R (GLn.coordRing R n)` instance, so we cannot use
`specObjOver` directly). -/
noncomputable def GLn.over (R : CommRingCat.{u}) (n : ℕ) :
    Over (Scheme.Spec.obj (op R)) :=
  Over.mk
    (Scheme.Spec.map (op (CommRingCat.ofHom
      (algebraMap R (GLn.coordRing R n)))))

/-- The underlying scheme of `GL_n`. -/
noncomputable abbrev GLnSch (R : CommRingCat.{u}) (n : ℕ) : Scheme.{u} :=
  (GLn.over R n).left

/-- `GLnSch R n` is canonically a scheme over `Spec R`. -/
noncomputable instance (R : CommRingCat.{u}) (n : ℕ) :
    (GLnSch R n).Over (Scheme.Spec.obj (op R)) :=
  ⟨(GLn.over R n).hom⟩

/-- The structure morphism is affine (it's `Spec.map` of a ring hom). -/
noncomputable instance (R : CommRingCat.{u}) (n : ℕ) :
    IsAffineHom ((GLnSch R n) ↘ Scheme.Spec.obj (op R)) := by
  show IsAffineHom (Scheme.Spec.map _)
  infer_instance

/-- The coordinate ring of `GL_n` is finitely generated as an `R`-algebra:
generated by the `n²` polynomial variables `X_{ij}` plus the inverse
of the determinant. Hence the structure morphism is locally of finite
type. -/
noncomputable instance (R : CommRingCat.{u}) (n : ℕ) :
    LocallyOfFiniteType ((GLnSch R n) ↘ Scheme.Spec.obj (op R)) := by
  show LocallyOfFiniteType (Spec.map _)
  rw [HasRingHomProperty.Spec_iff (P := @LocallyOfFiniteType)]
  show RingHom.FiniteType (algebraMap R (GLn.coordRing R n))
  rw [RingHom.finiteType_algebraMap]
  -- GLn.coordRing R n = Localization.Away det, which is finitely
  -- generated over R since MvPolynomial is (by n² generators) and
  -- Localization.Away adjoins one inverse.
  show Algebra.FiniteType R (Localization.Away (GLn.det R n))
  -- MvPolynomial in finitely many vars is FG over R; localization at
  -- any element preserves FG.
  haveI : Algebra.FiniteType R (MvPolynomial (Fin n × Fin n) R) :=
    inferInstance
  exact instFiniteTypeAway (GLn.det R n)

/-! ### Future work: the Hopf algebra structure

To upgrade `GLn R n` to an `IsAlgebraicGroup`, the following pieces are
needed:

* `GLn.comul : GLn.coordRing R n →ₐ[R] (GLn.coordRing R n) ⊗[R] (GLn.coordRing R n)`
  sending `X_{ij} ↦ ∑_k X_{ik} ⊗ X_{kj}`.
* `GLn.counit : GLn.coordRing R n →ₐ[R] R` sending `X_{ij} ↦ δ_{ij}`.
* `GLn.antipode : GLn.coordRing R n →ₐ[R] GLn.coordRing R n` via Cramer's
  rule (involves the adjugate matrix and `det^{-1}`).
* Bialgebra + Hopf axioms (each reduces to an equation on generators
  `X_{ij}`, verifiable by matrix-multiplication computation).

The construction is documented in any standard reference (e.g.,
Waterhouse "Introduction to Affine Group Schemes", §1.5) but the
formalization is ~300-500 LoC. Tracked in blueprint
`linear_algebraic_groups.general_linear_group_scheme` (status:
`admitted`, awaiting Lean implementation).

Once installed, the IsAlgebraicGroup instance follows automatically
via `hopfSpecGrpObj` (the same pattern as `Ga`, `Gm`, `μ_n`). -/

end Langlands.AlgebraicGeometry.Examples
