import LanglandsLean.AlgebraicGeometry.HopfSpec
import LanglandsLean.AlgebraicGeometry.AlgHomPointsPresheaf
import LanglandsLean.AlgebraicGeometry.IsAlgebraicGroup
import Mathlib.RingTheory.HopfAlgebra.MonoidAlgebra
import Mathlib.Algebra.Polynomial.Laurent
import Mathlib.AlgebraicGeometry.Morphisms.Affine
import Mathlib.AlgebraicGeometry.Morphisms.FiniteType
import Mathlib.RingTheory.FiniteType

/-!
# The multiplicative group scheme `G_m`

For a commutative ring `R`, the multiplicative group scheme
\(\mathbb{G}_{m,R} = \operatorname{Spec} R[T, T^{-1}]\) is constructed
via `hopfSpec` from Mathlib's
`LaurentPolynomial.instHopfAlgebra : HopfAlgebra R (R[T;T⁻¹])`
(group-like comultiplication `Δ(T) = T ⊗ T`, counit `ε(T) = 1`,
antipode `S(T) = T⁻¹`).

This is the **first concrete example** verifying the Yoneda hopfSpec
chain end-to-end on an actual algebraic group.

## Main declarations

* `multiplicativeGroup R` — `Spec R[T;T⁻¹]` as a scheme over `Spec R`.
* `multiplicativeGroup.instGrpObj R` — the group-object structure on
  `multiplicativeGroup R`, inherited from the Hopf algebra structure
  on `R[T;T⁻¹]` via `hopfSpecGrpObj`.

## Blueprint

`linear_algebraic_groups.multiplicative_group_scheme`.

## GitHub issue

Phase D2: <https://github.com/Langlandsproject/Langlands/issues/7>.
-/

open AlgebraicGeometry CategoryTheory Opposite LaurentPolynomial
open Langlands.AlgebraicGeometry.AlgHomPointsPresheaf

namespace Langlands.AlgebraicGeometry.Examples

universe u

variable (R : CommRingCat.{u})

/-- The Hopf algebra `R[T;T⁻¹]` of Laurent polynomials, packaged as a
commutative `R`-algebra. Its Hopf structure is from Mathlib's
`LaurentPolynomial.instHopfAlgebra`. -/
noncomputable abbrev multiplicativeGroup.hopfAlg :
    CommAlgCat.{u} R :=
  CommAlgCat.of R (LaurentPolynomial R)

/-- The multiplicative group scheme `G_{m,R} = Spec R[T;T⁻¹]` over
`Spec R`, viewed as an object of `Over (Spec R)`. -/
noncomputable def multiplicativeGroup :
    Over (Scheme.Spec.obj (op R)) :=
  specObjOver R (LaurentPolynomial R)

/-- The group-object structure on `multiplicativeGroup R = Spec R[T;T⁻¹]`,
inherited from the Hopf algebra structure on `R[T;T⁻¹]` via the Yoneda
construction `hopfSpecGrpObj`. -/
noncomputable instance multiplicativeGroup.instGrpObj :
    GrpObj (multiplicativeGroup R) :=
  hopfSpecGrpObj R (LaurentPolynomial R)

/-! ### Project-convention packaging: `IsAffineGroupScheme` instance

The Yoneda construction above gives `GrpObj` on the `Over (Spec R)`
object directly. Re-expose it under the project's typeclass convention
`(G : Scheme) [G.Over S] [GrpObj (Scheme.asOver G S)]`. -/

/-- The underlying scheme of `multiplicativeGroup R`: `Spec R[T;T⁻¹]`. -/
noncomputable abbrev Gm : Scheme.{u} := (multiplicativeGroup R).left

/-- `Gm R` is canonically a scheme over `Spec R` via the structure
morphism of `multiplicativeGroup R`. -/
noncomputable instance : (Gm R).Over (Scheme.Spec.obj (op R)) :=
  ⟨(multiplicativeGroup R).hom⟩

/-- The `GrpObj` on `Scheme.asOver (Gm R) (Spec R)` agrees definitionally
with the one already shipped on `multiplicativeGroup R`. -/
noncomputable instance : GrpObj (Scheme.asOver (Gm R) (Scheme.Spec.obj (op R))) :=
  multiplicativeGroup.instGrpObj R

/-- The structure morphism `Gm R ↘ Spec R = Spec.map (algebraMap R R[T;T⁻¹])`
is affine (it is the Spec of a ring map). -/
noncomputable instance : IsAffineHom ((Gm R) ↘ Scheme.Spec.obj (op R)) := by
  show IsAffineHom (Scheme.Spec.map _)
  infer_instance

/-- `Gm R` is an affine group scheme over `Spec R`, in the
project-convention sense (Path 4 + Level 1 aggregator). -/
noncomputable instance : IsAffineGroupScheme (Gm R) (Scheme.Spec.obj (op R)) :=
  inferInstance

/-- The structure morphism is locally of finite type: `R[T;T⁻¹]` is a
finitely-generated `R`-algebra (generated by `T` and `T⁻¹`). -/
noncomputable instance :
    LocallyOfFiniteType ((Gm R) ↘ Scheme.Spec.obj (op R)) := by
  show LocallyOfFiniteType (Spec.map _)
  rw [HasRingHomProperty.Spec_iff (P := @LocallyOfFiniteType)]
  show RingHom.FiniteType (algebraMap R (LaurentPolynomial R))
  rw [RingHom.finiteType_algebraMap]
  -- LaurentPolynomial R = AddMonoidAlgebra R ℤ, which is finitely
  -- generated since ℤ = AddGroup.FG (generated by 1).
  exact AddMonoidAlgebra.finiteType_of_fg R ℤ

/-- `Gm R` is an **algebraic group** over `Spec R`. -/
noncomputable instance : IsAlgebraicGroup (Gm R) (Scheme.Spec.obj (op R)) :=
  inferInstance

end Langlands.AlgebraicGeometry.Examples
